### ISSUE TITLE
Need Accept: application/vnd.api.v2+json in request headers

### ISSUE THREAD

**Issue by oshemkov** [andrey-tech/yclients-api-php#1]
New API requirement: Accept header in request.

Please replace
`$headers = [ 'Content-Type: application/json' ];`
to
`$headers = [ 'Content-Type: application/json', 'Accept: application/vnd.api.v2+json' ];`

**Comment by andrey-tech** [comment]
Fixed in release: [v1.7.7](https://github.com/andrey-tech/yclients-api-php/releases/tag/1.7.7).
